declare module "@spore/orchestrator" {
  export {
    createExecution,
    getExecutionDetail,
    listExecutionEvents,
    spawnExecutionBranches,
  } from "./execution/workflow-execution.js";

  export { planWorkflowInvocation } from "./invocation/plan-workflow-invocation.js";

  export { transitionStepRecord } from "./lifecycle/execution-lifecycle.js";

  export {
    getRegressionLatestReport,
    getRegressionRunReport,
    getRegressionRunSummaryById,
    getRegressionSchedulerStatus,
    getRegressionTrends,
    getRunCenterSummary,
    getScenarioRunArtifacts,
    getScenarioRunSummaryById,
    getScenarioTrends,
  } from "./scenarios/run-history.js";

  export {
    approveProposalArtifact,
    cleanupManagedWorkspace,
    createSelfBuildOverride,
    createGoalPlan,
    createManagedWorkItem,
    editGoalPlan,
    getDocSuggestionSummary,
    getDocSuggestionsForRun,
    getGoalPlanHistory,
    getGoalPlanSummary,
    getIntegrationBranchSummary,
    getPolicyRecommendationSummary,
    getProposalReviewPackage,
    getProposalByRun,
    getProposalSummary,
    getSelfBuildLearningTrends,
    getSelfBuildIntakeSummary,
    listPolicyRecommendationReviewSummaries,
    listSelfBuildDecisionSummaries,
    listSelfBuildDocSuggestionSummaries,
    getSelfBuildDashboard,
    getSelfBuildLoopStatus,
    getSelfBuildOverrideSummary,
    listSelfBuildOverrideSummaries,
    getSelfBuildPolicyRecommendations,
    listSelfBuildIntakeSummaries,
    listSelfBuildLearningSummaries,
    listSelfBuildQuarantineSummaries,
    listSelfBuildRollbackSummaries,
    getSelfBuildSummary,
    getSelfBuildWorkItem,
    getSelfBuildWorkItemRun,
    getWorkItemGroupSummary,
    getWorkItemTemplate,
    getWorkspaceDetail,
    getWorkspaceDetailByRun,
    listIntegrationBranchSummaries,
    listExecutionWorkspaces,
    listGoalPlansSummary,
    listSelfBuildWorkItemRuns,
    listSelfBuildWorkItems,
    listWorkItemGroupsSummary,
    listWorkItemTemplates,
    listWorkspaceSummaries,
    materializePolicyRecommendation,
    materializeDocSuggestionRecord,
    materializeGoalPlan,
    materializeSelfBuildIntake,
    planProposalPromotion,
    quarantineSelfBuildTarget,
    requeueWorkItemGroupItem,
    reconcileManagedWorkspace,
    refreshSelfBuildIntake,
    releaseSelfBuildQuarantine,
    releaseSelfBuildOverride,
    rollbackIntegrationBranch,
    rerouteWorkItemGroup,
    retryDownstreamWorkItemGroup,
    rerunSelfBuildWorkItemRun,
    reviewPolicyRecommendation,
    reviewDocSuggestionRecord,
    reviewGoalPlan,
    reviewProposalArtifact,
    reviewSelfBuildOverride,
    reviewSelfBuildIntake,
    reworkProposalArtifact,
    runGoalPlan,
    runSelfBuildWorkItem,
    runWorkItemGroup,
    setWorkItemGroupDependencies,
    skipWorkItemGroupItem,
    startSelfBuildLoop,
    stopSelfBuildLoop,
    unblockWorkItemGroup,
    invokeProposalPromotion,
    validateWorkItemGroupBundle,
    validateWorkItemRun,
  } from "./self-build/self-build.js";

  export {
    getProposalArtifact,
    getWorkItem,
    openOrchestratorDatabase,
    updateStep,
    updateProposalArtifact,
    updateWorkItem,
  } from "./store/execution-store.js";
}
